compiler/natives/src/syscall: Provide implementation of Exit.
syscall.Exit implementation has been removed upstream. In Go 1.10, it's
provided via runtime.exit. We can't do that, so just implement
syscall.Exit ourselves as it was previously implemented.

Related to https://github.com/golang/go/commit/438c8f6b531a1cfcb4a084d3090b631938a9839e.

Fixes:

	Error: runtime error: native function not implemented: syscall.Exit